version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: gemini-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  server:
    build: ./server
    container_name: gemini-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: gemini-client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data: 